### ISSUE TITLE
[文章相關] 第 1 部分 Objective-C 與 C

### ISSUE THREAD

**Issue by the-yuyut** [ytyubox/ithelp_from_swift_learn_objc#9]
## 檢查項目
- [x] 要修改什麼： 1️⃣ 大綱 / 主題 / 筆記 
- [x] 草稿有了嗎？
- [x] Branch建立了嗎？

## 描述

管理第 1 部分的文章
- [x] 01 介紹 Objective-C  #4 
- [x] 02 Objective-C 的 C 語言部分 （編譯器） #12 
- [x] 03 Objective-C 的基本 C 語言型別 #14 
- [x] 04 Objective-C 的基本 C 語言 Array、String #16 
- [x] 05 Objective-C 的基本 C 語言 Function #19 
- [x] 06 Objective-C 的基本 C 語言 Control flow #21 
- [ ] 07 Objective-C 的基本 C 語言 library 使用
- [ ] 08 Objective-C 的基本困難 C 語言 malloc、free
- [ ] 09 Objective-C 的基本困難 C 語言 Preprocessor
- [ ] 10 Objective-C 的基本困難 C 語言 自定義 Header 

## 備註

https://courses.cs.washington.edu/courses/cse351/16wi/sections/1/Cheatsheet-c.pdf
以下空白。

**Comment by ytyubox** [comment]
02 Objective-C 的 C 語言部分 （編譯器）
開始規劃

**Comment by ytyubox** [comment]
#13
